package io.github.stellnula.domain;

import java.time.OffsetDateTime;

public record ConfigRecord(
    String configId,
    String configName,
    String ownerType,
    String ownerId,
    String namespaceCode,
    String groupCode,
    String contentType,
    boolean sensitive,
    long scopeId,
    String env,
    String region,
    String zone,
    String cluster,
    String scopeMode,
    String releaseNo,
    long version,
    long revision,
    String content,
    String checksum,
    String releaseStatus,
    OffsetDateTime releasedAt,
    String governanceRuleType,
    String governanceTargetService,
    String governanceStatus,
    Integer governancePriority) {

  public ConfigRecord(
      String configId,
      String configName,
      String ownerType,
      String ownerId,
      String namespaceCode,
      String groupCode,
      String contentType,
      boolean sensitive,
      long scopeId,
      String env,
      String region,
      String zone,
      String cluster,
      String scopeMode,
      String releaseNo,
      long version,
      long revision,
      String content,
      String checksum,
      String releaseStatus,
      OffsetDateTime releasedAt) {
    this(
        configId,
        configName,
        ownerType,
        ownerId,
        namespaceCode,
        groupCode,
        contentType,
        sensitive,
        scopeId,
        env,
        region,
        zone,
        cluster,
        scopeMode,
        releaseNo,
        version,
        revision,
        content,
        checksum,
        releaseStatus,
        releasedAt,
        null,
        null,
        null,
        null);
  }
}
